# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

soundcloud:         &soundcloud
  sc_client_id:     'ad6c28bf8fae772613fade134b337e42'
  sc_client_secret: '00df6ab41d7b897e2b4f528885bedccb'

development:
  <<: *soundcloud
  secret_key_base: 3b3004ff594c6de4fa5fef411eb1271eb0d4786c5c3983bcf1e9f4ab435443b7fe345edc7e2ece986685dc7383d2f59d4ea964d36baa0955b29456fe115bca8c

test:
  <<: *soundcloud
  secret_key_base: 47fc2b88721c05cb21602343af1f48a49d5fc665af853aa1bb0ed5a3c2a9c2396eaf9ffa8611037ac9327fe5c559501aa35457eeb83e3ccf6720abc662812d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *soundcloud
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
